STYLE = {
    "marble_yoga": {
        "folder": "3_AI画廊_大理石瑜伽_16体式",
        "subjects": [
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing king pigeon pose, one leg bent back, body arched gracefully, full body visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing warrior pose II, lunge, arms extended parallel to the ground, full body visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing bow pose, lying on stomach, hands pulling feet, body arched like a bow, full body visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing tree pose, standing on one leg, hands clasped above head, full body visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing thunderbolt pose, kneeling, hands resting on knees, meditating, full body visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing upward facing dog pose, chest open, arms straight, legs extended, full body visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing dancer pose, standing on one leg, holding back foot with hand, body arched gracefully, full body visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing headstand, balancing on forearms, legs straight up in the air, inverted pose, full body visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing half moon pose, balancing on one leg and one hand, body extended sideways, full body visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing headstand with legs crossed, balancing on forearms, legs intertwined in air, full body visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing crane pose, balancing on hands, knees resting on upper arms, focused look, full body visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, two beautiful women, pure white marble statues, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing partner acroyoga, one standing on the other's back, balancing beautifully, full bodies visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing camel pose, kneeling, arching back, hands reaching heels, chest open, intense stretch, full body visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing warrior pose I, lunge stance, arms raised straight up, looking forward, full body visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing standing forward fold, bending forward from the hips, hands reaching to the ground, full body visible, high quality, photorealistic, masterpiece",
            "masterpiece, best quality, photorealistic, 8k, a beautiful woman, pure white marble statue, flawless white marble, monochrome white, classical sculpture, intricate carving details, smooth stone texture, dramatic lighting, doing wheel pose, hands and feet on the ground, body arched like a bridge, full body visible, high quality, photorealistic, masterpiece"
        ],
        "strength": 0.40
    }
}