STYLE = {
    "remove_clothes_v2": {
        "folder": "7_其他_去衣服_分层",
        "strength": 0.50,
        
        "subjects": [
            "nude woman, bare skin, beach, ocean waves",
            "nude woman, pool side, water reflections",
            "nude woman, luxury yacht, ocean background",
            "nude woman, hot spring, steam rising",
            "nude woman, yoga pose, flexible body",
            "nude woman, gym, fit body, defined muscles",
            "nude woman, running, dynamic pose",
            "nude woman, modern office, professional",
            "nude woman, urban street, confident",
            "nude woman, snowy landscape, contrast",
            "nude woman, red carpet, glamorous",
            "nude woman, flower garden, natural beauty",
            "nude woman, home, cozy atmosphere",
            "nude woman, forest, natural sunlight",
            "nude woman, white sheets, soft lighting",
            "nude woman, yacht deck, glamorous",
            "nude woman, couch, soft lighting",
            "nude woman, hotel room, warm lighting",
            "nude woman, window, natural light",
            "nude woman, bathtub, water, steam",
            "nude woman, studio, professional lighting",
            "nude woman, bed, morning light",
            "nude woman, garden, flowers, sunlight",
            "nude woman, mountain, landscape",
            "nude woman, waterfall, water, nature",
            "nude woman, resort, pool, palm trees",
        ],
        
        "styles": [
            "golden sunset, sun-kissed skin",
            "summer atmosphere, warm lighting",
            "golden lighting, glamorous",
            "natural rock background, relaxing",
            "peaceful atmosphere, natural lighting",
            "workout atmosphere, natural lighting",
            "outdoor setting, dramatic lighting",
            "professional setting, dramatic lighting",
            "city atmosphere, dramatic lighting",
            "winter atmosphere, snow contrast",
            "dramatic lighting, elegant pose",
            "soft lighting, natural beauty",
            "cozy atmosphere, soft lighting",
            "forest background, artistic",
            "soft lighting, intimate",
            "sea background, glamorous",
            "soft lighting, intimate",
            "warm lighting, luxurious",
            "natural light, elegant",
            "water, steam, artistic",
            "soft lighting, professional",
            "morning light, natural",
            "sunlight, vibrant nature",
            "landscape, outdoor beauty",
            "water, nature, artistic",
            "pool, tropical vacation",
        ],
        
        "moods": [
            "natural and free",
            "glamorous and sensual",
            "peaceful and relaxed",
            "confident and powerful",
            "beautiful and artistic",
            "intimate and natural",
        ],
    }
}